### PR TITLE
Update floating_filters.txt

### PR DESCRIPTION
**Pull request by Sonic5435325**
Quick fix to https://github.com/LanikSJ/webannoyances/issues/228 and a bunch of other display/sticky issues on `Gitlab.com`

### CODE REVIEW

**Comment by Sonic5435325** [comment]
This should fix it. If not, let me know if the problem persists

**Review by LanikSJ — APPROVED** [review]

**Comment by LanikSJ** [comment]
Thank you 👍 😁

**Comment by Sonic5435325** [comment]
Do `gitlab.com##.issuable-sidebar.is-merge-request .issuable-context-form:style(position: relative !important; top: 0 !important;) `and `gitlab.com##.merge-request-sticky-header` work fine for you as replacements to the removed filters?

**Comment by LanikSJ** [comment]
Yes I think I'm good I've tested it several times today.

**Pull request merged**
