### PR TITLE
Sonic5435325 patch 1

### PR DESCRIPTION
**Pull request by Sonic5435325**

### CODE REVIEW

**Review by LanikSJ — APPROVED** [review]

**Review by LanikSJ — APPROVED** [review]

**Comment by LanikSJ** [comment]
@Sonic5435325 Looks there are some style failures https://restyled.io/gh/LanikSJ/repos/webannoyances/jobs/4418124/patch

**Comment by Sonic5435325** [comment]
I'm confused, does `popularmechanics.com##journey-modal-newsletter[data-template-id="pop-modal-newsletter"]` have to be removed

**Comment by LanikSJ** [comment]
Is it me or both lines look the same. The line to be removed and the line to be added.

**Comment by Sonic5435325** [comment]
These aren't the same
`pornhub.com##body:style(overflow: auto !important;)`
`pornhub.com###ageDisclaimerMainBG, .fadeInMTubes`

**Comment by LanikSJ** [comment]
There's an extra white space at the end of that line that's what it's complaining about.

**Comment by Sonic5435325** [comment]
Do I need to redo the PR?

**Comment by LanikSJ** [comment]
Nope you're good now.

**Pull request merged**
