### PR TITLE
Sonic5435325 patch 1

### PR DESCRIPTION
**Pull request by Sonic5435325**

### CODE REVIEW

**Comment by Sonic5435325** [comment]
I don't know what's causing the conflicts, but here's another update.

**Review by LanikSJ — APPROVED** [review]

**Comment by LanikSJ** [comment]
There was an automated job that just merged something. My suggestion is to rebase your changes.

**Comment by Sonic5435325** [comment]
I think that should be a sufficient enough change

**Comment by LanikSJ** [comment]
Yup that did it

**Pull request merged**
