### PR TITLE
Sonic5435325 patch 2

### PR DESCRIPTION
**Pull request by Sonic5435325**

### CODE REVIEW

**Comment by LanikSJ** [comment]
@Sonic5435325 this won't show on master.

**Comment by Sonic5435325** [comment]
I'll just do another

**Comment by Sonic5435325** [comment]
@LanikSJ Could probably just delete the extra branch. Won't be needed anyways. Don't know why it made that here, didn't mean for it to happen lmao

**Comment by LanikSJ** [comment]
It's shows up under your fork so I can't remove it sadly.

**Comment by Sonic5435325** [comment]
The branch was removed from my fork

**Pull request merged**
